### ISSUE TITLE
Authorization header: Don't set when logged out

### ISSUE THREAD

**Issue by marczych** [iFixit/iFixit-iOS#39]
We're seeing requests to our backend with this header: `Authorization: api (null)`. The Authorization header should only be set if the user is logged in.

See [this](https://github.com/iFixit/iFixit-iOS/blob/d751c11bf68ccd14576a26f6526ecfd2045f53e7/Classes/iFixitAPI.m#L117) and the other dozen places that will have to be updated.

**Comment by BaseInfinity** [comment]
Good sleuthing! Will be fixed whenever we update the app
