### ISSUE TITLE
Bullet text cut off in iOS 8+

### ISSUE THREAD

**Issue by kwiens** [iFixit/iFixit-iOS#54]
We're working on narrowing down the list of operating systems, but we have reproduced this in iOS 8.3.

There are a few different issues. First:
* Navigate to a guide in landscape view
* The right half of the introduction is cut off

Second:
* Open a guide in portrait view
* Navigate to a step with multiple bullets
* Rotate into landscape. Everything is happy.
* Rotate into portrait. Bullets underneath the first one are clipped. Scrolling in the text area reveals the hidden bullets.

![img_0130](https://cloud.githubusercontent.com/assets/14790958/10089945/59b9a290-62de-11e5-9263-24316c4be996.png)

There are more rotation bugs in these new OSs. Would you like us to exhaustively test and give you a list of all of them, or do they all have the same underlying fix?

**Comment by amandaradakovich** [comment]
https://apps.rackspace.com/a/attachments/INBOX/63/2?wsid=b00517802c008f8640c0b972460fb677df7c04ee
https://apps.rackspace.com/a/attachments/INBOX/62/2?wsid=b00517802c008f8640c0b972460fb677df7c04ee
![img_0130](https://cloud.githubusercontent.com/assets/14790958/10089945/59b9a290-62de-11e5-9263-24316c4be996.png)

**Comment by amandaradakovich** [comment]
![img_0129](https://cloud.githubusercontent.com/assets/14790958/10090008/f74620e2-62de-11e5-815d-ddddbe440f7b.PNG)
![img_0131](https://cloud.githubusercontent.com/assets/14790958/10090010/fea590f2-62de-11e5-8435-3ced7a5c38ab.PNG)

**Comment by amandaradakovich** [comment]
![image](https://cloud.githubusercontent.com/assets/14790958/10090023/2edb3bdc-62df-11e5-8ea4-14666e6fe09f.png)
