### ISSUE TITLE
Update Categories to Use Display Title 

### ISSUE THREAD

**Issue by amandaradakovich** [iFixit/iFixit-iOS#60]
The iOS app displays all categories using the original page title for the category, whereas the desktop site and Android app use the Display Title to display categories throughout the site. The iOS app should be updated to use the Display Titles as well. 

Example Category: https://gunnerautomotive.dozuki.com/c/Work_Instructions

In Android, it shows as "Assembly" (display title) 
![screenshot_20170609-212343_720](https://user-images.githubusercontent.com/14790958/26991428-90c674da-4d5a-11e7-93e6-b4d344d5f400.png)

In iOS, it shows as "Work Instructions" (page title) 
![img_0136_720](https://user-images.githubusercontent.com/14790958/26991427-90c06f04-4d5a-11e7-94d3-8e520672befc.jpg)

**Comment by Airruk** [comment]
That's odd  - I show that the ios version actually shows the display title when viewing it on the iPhone - I wouldn't have thought that the ways those menus are populated would differ between iphone and ipad.
